Repository Konkuk-KUIT/KUIT4_WEB-Frontend, pull requests merged in 2024-09, with the labels that each got.

#7 [1주차] 자기소개 HTML
  week1/turtlehwan/index.css
  week1/turtlehwan/index.html
Labels: 김지환

#10 [1주차] 자기소개 HTML
  week1/fr0gydev/index.html
Labels: 이지현

#13 [1주차] 자기소개 HTML
  week1/uchan0/index.html
Labels: 유찬영

#11 [1주차] 자기소개 HTML
  week1/FrogUni/index.html
Labels: 노원우

#14 [1주차] 자기소개 HTML
  week1/hamxxn/index.html
Labels: 권동희

#15 [1주차] 자기소개 HTML
  week1/seokjin/index.html
Labels: 김석진

#16 [1주차] 자기소개 HTML
  week1/jisung/index.html
Labels: 임지성

#12 [1주차] 자기소개 HTML
  week1/heeedragon/index.html
Labels: 김희용

#17 index.html 생성 (김지예)
  week1/jiyeKa/index.html
Labels: 김지예

#9 [1주차] 자기소개 HTML
  week1/gyuun/index.html
Labels: 황규운

#18 [1주차] 자기소개 HTML
  week1/hyungyu/index.html
Labels: 고현규

#19 [1주차] 자기소개 HTML
  week1/rlawngP91/index.html
Labels: 김주혜

#20 [1주차] 자기소개 HTML
  week1/hyunju/index.html
Labels: 이현주

#41 3주차 예제, 실습, 미션 코드 베이스
  week3/jinho1011/babel/index.js
  week3/jinho1011/babel/package-lock.json
  week3/jinho1011/babel/package.json
  week3/jinho1011/es6/index.js
  week3/jinho1011/todo/app.js
  week3/jinho1011/todo/db.json
  week3/jinho1011/todo/index.css
  week3/jinho1011/todo/index.html
Labels: 김지환

#26 [2주차] 당근마켓 클론 미션 화면1, 2
  week2/gyuun/assets/advertising.svg
  week2/gyuun/assets/battery.svg
  week2/gyuun/assets/blackbox.svg
  week2/gyuun/assets/happy.svg
  week2/gyuun/assets/home.svg
  week2/gyuun/assets/home2.svg
  week2/gyuun/assets/home3.svg
  week2/gyuun/assets/home4.svg
  week2/gyuun/assets/home5.svg
  week2/gyuun/assets/home_indicator.svg
  week2/gyuun/assets/leftwallet.svg
  week2/gyuun/assets/location.svg
  week2/gyuun/assets/middle_tag_icon.svg
  week2/gyuun/assets/middle_tag_user.svg
  week2/gyuun/assets/ok.svg
  week2/gyuun/assets/plus.svg
  week2/gyuun/assets/rightwallet.svg
  week2/gyuun/assets/see.svg
  week2/gyuun/assets/signal.svg
  week2/gyuun/assets/speech.svg
  week2/gyuun/assets/tran.svg
  week2/gyuun/assets/vector.svg
  week2/gyuun/assets/vectors.svg
  week2/gyuun/assets/wify.svg
  week2/gyuun/index.css
  week2/gyuun/index.html
  week2/gyuun/reset.css
  week2/gyuun2/assets/battery.svg
  week2/gyuun2/assets/blackbox.svg
  week2/gyuun2/assets/comment.svg
  week2/gyuun2/assets/content1.svg
  week2/gyuun2/assets/content2.svg
  week2/gyuun2/assets/content3.svg
  week2/gyuun2/assets/content4.svg
  week2/gyuun2/assets/heart.svg
  week2/gyuun2/assets/home.svg
  week2/gyuun2/assets/home2.svg
  week2/gyuun2/assets/home3.svg
  week2/gyuun2/assets/home4.svg
  week2/gyuun2/assets/home5.svg
  week2/gyuun2/assets/home_indicator.svg
  week2/gyuun2/assets/plus.svg
  week2/gyuun2/assets/see.svg
  week2/gyuun2/assets/signal.svg
  week2/gyuun2/assets/tran.svg
  week2/gyuun2/assets/vector.svg
  week2/gyuun2/assets/vectors.svg
  week2/gyuun2/assets/wify.svg
  week2/gyuun2/index.css
  week2/gyuun2/index.html
  week2/gyuun2/reset.css
Labels: 황규운

#27 [2주차] 당근마켓 화면1 미션
  week2/uchan0/mission/assets/airpod.svg
  week2/uchan0/mission/assets/bell.svg
  week2/uchan0/mission/assets/chat.svg
  week2/uchan0/mission/assets/coffeemachine.svg
  week2/uchan0/mission/assets/down-chevron.svg
  week2/uchan0/mission/assets/hamburger.svg
  week2/uchan0/mission/assets/heart.svg
  week2/uchan0/mission/assets/home.svg
  week2/uchan0/mission/assets/iphone13.svg
  week2/uchan0/mission/assets/life.svg
  week2/uchan0/mission/assets/mydaangn.svg
  week2/uchan0/mission/assets/nearby.svg
  week2/uchan0/mission/assets/plus.svg
  week2/uchan0/mission/assets/product2.svg
  week2/uchan0/mission/assets/sandwich.svg
  week2/uchan0/mission/assets/search.svg
  week2/uchan0/mission/assets/smallChat.svg
  week2/uchan0/mission/index.css
  week2/uchan0/mission/index.html
  week2/uchan0/mission/reset.css
  week2/uchan0/practice/assets/heart.svg
  week2/uchan0/practice/assets/home.svg
  week2/uchan0/practice/assets/kebab.svg
  week2/uchan0/practice/assets/left-chevron.svg
  week2/uchan0/practice/assets/right-chevron.svg
  week2/uchan0/practice/assets/share.svg
  week2/uchan0/practice/index.css
  week2/uchan0/practice/index.html
  week2/uchan0/practice/reset.css
Labels: 유찬영

#28 [2주차] 당근마켓 화면1 미션
  week1/heeedragon/index.html
  week1/heeyong/index.html
  week2/heeedragon/daangn/기존 구현 파일/index.css
  week2/heeedragon/daangn/기존 구현 파일/index.html
  week2/heeedragon/daangn/기존 구현 파일/practice.css
  week2/heeedragon/daangn/기존 구현 파일/practice.html
  week2/heeedragon/daangn/기존 구현 파일/reset.css
  week2/heeedragon/daangn/미션용/assets/bottom-chat.svg
  week2/heeedragon/daangn/미션용/assets/bottom-home.svg
  week2/heeedragon/daangn/미션용/assets/chat.svg
  week2/heeedragon/daangn/미션용/assets/down-chevron.svg
  week2/heeedragon/daangn/미션용/assets/hamburger.svg
  week2/heeedragon/daangn/미션용/assets/heart.svg
  week2/heeedragon/daangn/미션용/assets/home.svg
  week2/heeedragon/daangn/미션용/assets/kebab.svg
  week2/heeedragon/daangn/미션용/assets/left-chevron.svg
  week2/heeedragon/daangn/미션용/assets/like.svg
  week2/heeedragon/daangn/미션용/assets/local.svg
  week2/heeedragon/daangn/미션용/assets/my.svg
  week2/heeedragon/daangn/미션용/assets/news.svg
  week2/heeedragon/daangn/미션용/assets/notification.svg
  week2/heeedragon/daangn/미션용/assets/plus.svg
  week2/heeedragon/daangn/미션용/assets/plusmath.svg
  week2/heeedragon/daangn/미션용/assets/product1.svg
  week2/heeedragon/daangn/미션용/assets/product2.svg
  week2/heeedragon/daangn/미션용/assets/product3.svg
  week2/heeedragon/daangn/미션용/assets/product4.svg
  week2/heeedragon/daangn/미션용/assets/product5.svg
  week2/heeedragon/daangn/미션용/assets/right-chevron.svg
  week2/heeedragon/daangn/미션용/assets/search.svg
  week2/heeedragon/daangn/미션용/assets/share.svg
  week2/heeedragon/daangn/미션용/index.css
  week2/heeedragon/daangn/미션용/index.html
  week2/heeedragon/daangn/실습용/assets/bottom-chat.svg
  week2/heeedragon/daangn/실습용/assets/bottom-home.svg
  week2/heeedragon/daangn/실습용/assets/chat.svg
  week2/heeedragon/daangn/실습용/assets/down-chevron.svg
  week2/heeedragon/daangn/실습용/assets/hamburger.svg
  week2/heeedragon/daangn/실습용/assets/heart.svg
  week2/heeedragon/daangn/실습용/assets/home.svg
  week2/heeedragon/daangn/실습용/assets/kebab.svg
  week2/heeedragon/daangn/실습용/assets/left-chevron.svg
  week2/heeedragon/daangn/실습용/assets/like.svg
  week2/heeedragon/daangn/실습용/assets/local.svg
  week2/heeedragon/daangn/실습용/assets/my.svg
  week2/heeedragon/daangn/실습용/assets/news.svg
  week2/heeedragon/daangn/실습용/assets/notification.svg
  week2/heeedragon/daangn/실습용/assets/plus.svg
  week2/heeedragon/daangn/실습용/assets/plusmath.svg
  week2/heeedragon/daangn/실습용/assets/product1.svg
  week2/heeedragon/daangn/실습용/assets/product2.svg
  week2/heeedragon/daangn/실습용/assets/product3.svg
  week2/heeedragon/daangn/실습용/assets/product4.svg
  week2/heeedragon/daangn/실습용/assets/product5.svg
  week2/heeedragon/daangn/실습용/assets/right-chevron.svg
  week2/heeedragon/daangn/실습용/assets/search.svg
  week2/heeedragon/daangn/실습용/assets/share.svg
  week2/heeedragon/daangn/실습용/index.css
  week2/heeedragon/daangn/실습용/index.html
Labels: 김희용

#29 [2주차] 당근마켓 화면1 미션
  week2/fl0gydev/미션/assets/airpodspro.svg
  week2/fl0gydev/미션/assets/bell.svg
  week2/fl0gydev/미션/assets/chat.svg
  week2/fl0gydev/미션/assets/down-arrow.svg
  week2/fl0gydev/미션/assets/heart.svg
  week2/fl0gydev/미션/assets/home.svg
  week2/fl0gydev/미션/assets/iphone13promax.svg
  week2/fl0gydev/미션/assets/location.svg
  week2/fl0gydev/미션/assets/menu.svg
  week2/fl0gydev/미션/assets/message.svg
  week2/fl0gydev/미션/assets/news.svg
  week2/fl0gydev/미션/assets/nintendo.svg
  week2/fl0gydev/미션/assets/plus.svg
  week2/fl0gydev/미션/assets/search.svg
  week2/fl0gydev/미션/assets/user.svg
  week2/fl0gydev/미션/assets/바이레도.svg
  week2/fl0gydev/미션/assets/샌드위치.svg
  week2/fl0gydev/미션/index.css
  week2/fl0gydev/미션/index.html
  week2/fl0gydev/미션/reset.css
  week2/fl0gydev/실습/Readme.md
  week2/fl0gydev/실습/assets/7BA74D02-F13E-46EE-B6E1-748A372FE4CB.png
  week2/fl0gydev/실습/assets/heart.svg
  week2/fl0gydev/실습/assets/home.svg
  week2/fl0gydev/실습/assets/kebab.svg
  week2/fl0gydev/실습/assets/left-chevron copy.svg
  week2/fl0gydev/실습/assets/left-chevron.svg
  week2/fl0gydev/실습/assets/right-chevron.svg
  week2/fl0gydev/실습/assets/share.svg
  week2/fl0gydev/실습/index.css
  week2/fl0gydev/실습/index.html
  week2/fl0gydev/실습/reset.css
Labels: 이지현

#30 [2주차] 당근마켓 화면1 미션
  week2/junghyun/clone_mission/assets/chat-mini.svg
  week2/junghyun/clone_mission/assets/chat.svg
  week2/junghyun/clone_mission/assets/expand-arrow.svg
  week2/junghyun/clone_mission/assets/heart-mini.svg
  week2/junghyun/clone_mission/assets/home.svg
  week2/junghyun/clone_mission/assets/menu.svg
  week2/junghyun/clone_mission/assets/news.svg
  week2/junghyun/clone_mission/assets/notification.svg
  week2/junghyun/clone_mission/assets/place-marker.svg
  week2/junghyun/clone_mission/assets/plus.svg
  week2/junghyun/clone_mission/assets/search.svg
  week2/junghyun/clone_mission/assets/user.svg
  week2/junghyun/clone_mission/index.css
  week2/junghyun/clone_mission/index.html
  week2/junghyun/clone_mission/reset.css
  week2/junghyun/clone_practice/assets/heart.svg
  week2/junghyun/clone_practice/assets/home.svg
  week2/junghyun/clone_practice/assets/kebab.svg
  week2/junghyun/clone_practice/assets/left-chevron.svg
  week2/junghyun/clone_practice/assets/right-chevron.svg
  week2/junghyun/clone_practice/assets/share.svg
  week2/junghyun/clone_practice/index.css
  week2/junghyun/clone_practice/index.html
  week2/junghyun/clone_practice/reset.css
Labels: 고정현

#34 [2주차] 당근마켓 화면1 미션
  week2/Kjiw0n/clone/assets/heart.svg
  week2/Kjiw0n/clone/assets/home.svg
  week2/Kjiw0n/clone/assets/kebab.svg
  week2/Kjiw0n/clone/assets/left-chevron.svg
  week2/Kjiw0n/clone/assets/right-chevron.svg
  week2/Kjiw0n/clone/assets/share.svg
  week2/Kjiw0n/clone/index.css
  week2/Kjiw0n/clone/index.html
  week2/Kjiw0n/clone/reset.css
  week2/Kjiw0n/daangn/assests/Chat.svg
  week2/Kjiw0n/daangn/assests/Home.svg
  week2/Kjiw0n/daangn/assests/Menu.svg
  week2/Kjiw0n/daangn/assests/News.svg
  week2/Kjiw0n/daangn/assests/Notification.svg
  week2/Kjiw0n/daangn/assests/Place Marker.svg
  week2/Kjiw0n/daangn/assests/Rectangle 2.png
  week2/Kjiw0n/daangn/assests/Search.svg
  week2/Kjiw0n/daangn/assests/User.svg
  week2/Kjiw0n/daangn/assests/airpod.png
  week2/Kjiw0n/daangn/assests/comment.svg
  week2/Kjiw0n/daangn/assests/down-chevron.svg
  week2/Kjiw0n/daangn/assests/favorite.svg
  week2/Kjiw0n/daangn/assests/ipone.png
  week2/Kjiw0n/daangn/assests/perfume.png
  week2/Kjiw0n/daangn/assests/sandwich.png
  week2/Kjiw0n/daangn/index.css
  week2/Kjiw0n/daangn/index.html
  week2/Kjiw0n/daangn/reset.css
Labels: 김지원

#40 [2주차] 당근마켓 화면1 미션
  week2/sooa/assets/bottom-bar_chat.svg
  week2/sooa/assets/bottom-bar_home.svg
  week2/sooa/assets/bottom-bar_location.svg
  week2/sooa/assets/bottom-bar_mypage.svg
  week2/sooa/assets/bottom-bar_news.svg
  week2/sooa/assets/chat.svg
  week2/sooa/assets/down-chervon.svg
  week2/sooa/assets/heart.svg
  week2/sooa/assets/menu.svg
  week2/sooa/assets/notification.svg
  week2/sooa/assets/plus.svg
  week2/sooa/assets/production1.svg
  week2/sooa/assets/production2.svg
  week2/sooa/assets/production3.svg
  week2/sooa/assets/production4.svg
  week2/sooa/assets/production5.svg
  week2/sooa/assets/search.svg
  week2/sooa/index.css
  week2/sooa/index.html
  week2/sooa/reset.css
Labels: 이수아

#38 [2주차] 당근마켓 화면1 미션
  week2/hyungyu/assets/airpodsImg.svg
  week2/hyungyu/assets/blanche.svg
  week2/hyungyu/assets/chat.svg
  week2/hyungyu/assets/chatLarge.svg
  week2/hyungyu/assets/coffeeMachine.svg
  week2/hyungyu/assets/expandArrow.svg
  week2/hyungyu/assets/heart.svg
  week2/hyungyu/assets/home.svg
  week2/hyungyu/assets/iPhone13ProMax.svg
  week2/hyungyu/assets/menu.svg
  week2/hyungyu/assets/news.svg
  week2/hyungyu/assets/notification.svg
  week2/hyungyu/assets/placeMarker.svg
  week2/hyungyu/assets/plus.svg
  week2/hyungyu/assets/sandwich.svg
  week2/hyungyu/assets/search.svg
  week2/hyungyu/assets/user.svg
  week2/hyungyu/index.css
  week2/hyungyu/index.html
  week2/hyungyu/reset.css
Labels: 고현규

#36 [2주차] 당근마켓 화면1 미션
  week2/jisung/danggn1.css
  week2/jisung/danggn1.html
  week2/jisung/danggn5.css
  week2/jisung/danggn5.html
  week2/jisung/reset.css
Labels: 임지성

#35 week2 당근 페이지 1 구현
  week2/jiyeKa/assets/chat.svg
  week2/jiyeKa/assets/comment.svg
  week2/jiyeKa/assets/expand-arrow.svg
  week2/jiyeKa/assets/heart.svg
  week2/jiyeKa/assets/home.svg
  week2/jiyeKa/assets/menu.svg
  week2/jiyeKa/assets/news.svg
  week2/jiyeKa/assets/notification.svg
  week2/jiyeKa/assets/placeMarker.svg
  week2/jiyeKa/assets/plus.svg
  week2/jiyeKa/assets/product1.svg
  week2/jiyeKa/assets/product2.svg
  week2/jiyeKa/assets/product3.svg
  week2/jiyeKa/assets/product4.svg
  week2/jiyeKa/assets/search.svg
  week2/jiyeKa/assets/user.svg
  week2/jiyeKa/index.css
  week2/jiyeKa/index.html
Labels: 김지예
