Repository Konkuk-KUIT/KUIT4_WEB-Frontend, pull requests merged in 2024-11, with the labels that each got.

#84 [5주차] 수정, 삭제 메서드 구현
  week5/hamxxn/.gitignore
  week5/hamxxn/README.md
  week5/hamxxn/eslint.config.js
  week5/hamxxn/index.html
  week5/hamxxn/package-lock.json
  week5/hamxxn/package.json
  week5/hamxxn/public/vite.svg
  week5/hamxxn/src/App.jsx
  week5/hamxxn/src/FliterableProductTable.jsx
  week5/hamxxn/src/InputBar.jsx
  week5/hamxxn/src/ProductCategoryRow.jsx
  week5/hamxxn/src/ProductRow.jsx
  week5/hamxxn/src/ProductTable.jsx
  week5/hamxxn/src/SearchBar.jsx
  week5/hamxxn/src/main.jsx
  week5/hamxxn/vite.config.js
Labels: 권동희

#85 5주차 미션 완료!
  week5/gyuun/.gitignore
  week5/gyuun/README.md
  week5/gyuun/index.html
  week5/gyuun/package-lock.json
  week5/gyuun/package.json
  week5/gyuun/src/App.css
  week5/gyuun/src/App.jsx
  week5/gyuun/src/FilterableProductTable.jsx
  week5/gyuun/src/InputBar.jsx
  week5/gyuun/src/ProductCategoryRow.jsx
  week5/gyuun/src/ProductRow.jsx
  week5/gyuun/src/ProductTable.jsx
  week5/gyuun/src/SearchBar.jsx
  week5/gyuun/src/main.jsx
  week5/gyuun/vite.config.js
Labels: 황규운

#86 5주차 미션
  week5/uchan0/.gitignore
  week5/uchan0/README.md
  week5/uchan0/eslint.config.js
  week5/uchan0/index.css
  week5/uchan0/index.html
  week5/uchan0/package-lock.json
  week5/uchan0/package.json
  week5/uchan0/src/App.jsx
  week5/uchan0/src/FilterableProductTable.jsx
  week5/uchan0/src/InputBar.jsx
  week5/uchan0/src/ProductCategoryRow.jsx
  week5/uchan0/src/ProductRow.jsx
  week5/uchan0/src/ProductTable.jsx
  week5/uchan0/src/SearchBar.jsx
  week5/uchan0/src/main.jsx
  week5/uchan0/vite.config.js
Labels: 유찬영

#87 [5주차] 상품 삭제, 수정 버튼 추가하기
  week5/junghyun/.gitignore
  week5/junghyun/README.md
  week5/junghyun/eslint.config.js
  week5/junghyun/index.html
  week5/junghyun/package-lock.json
  week5/junghyun/package.json
  week5/junghyun/src/App.jsx
  week5/junghyun/src/FilterableProductTable.jsx
  week5/junghyun/src/InputBar.jsx
  week5/junghyun/src/ProductCategoryRow.jsx
  week5/junghyun/src/ProductRow.jsx
  week5/junghyun/src/ProductTable.jsx
  week5/junghyun/src/SearchBar.jsx
  week5/junghyun/src/main.jsx
  week5/junghyun/vite.config.js
Labels: 고정현

#88 5주차 delete구현 완료
  week5/seokjin/.gitignore
  week5/seokjin/README.md
  week5/seokjin/eslint.config.js
  week5/seokjin/index.html
  week5/seokjin/package-lock.json
  week5/seokjin/package.json
  week5/seokjin/public/vite.svg
  week5/seokjin/src/App.jsx
  week5/seokjin/src/FilterableProductTable.jsx
  week5/seokjin/src/InputBar.jsx
  week5/seokjin/src/ProductCategoryRow.jsx
  week5/seokjin/src/ProductRow.jsx
  week5/seokjin/src/ProductTable.jsx
  week5/seokjin/src/SearchBar.jsx
  week5/seokjin/src/main.jsx
  week5/seokjin/vite.config.js
Labels: 김석진

#99 [5주차] 제품 삭제, 편집 기능 구현
  week5/Kjiw0n/.gitignore
  week5/Kjiw0n/README.md
  week5/Kjiw0n/eslint.config.js
  week5/Kjiw0n/index.html
  week5/Kjiw0n/package-lock.json
  week5/Kjiw0n/package.json
  week5/Kjiw0n/public/vite.svg
  week5/Kjiw0n/src/App.jsx
  week5/Kjiw0n/src/FilterableProductTable.jsx
  week5/Kjiw0n/src/InputBar.jsx
  week5/Kjiw0n/src/ProductCategoryRow.jsx
  week5/Kjiw0n/src/ProductRow.jsx
  week5/Kjiw0n/src/ProductTable.jsx
  week5/Kjiw0n/src/SearchBar.jsx
  week5/Kjiw0n/src/main.jsx
  week5/Kjiw0n/vite.config.js
Labels: 김지원

#98 [5주차] 삭제 구현
  week5/seonghyeon/.gitignore
  week5/seonghyeon/README.md
  week5/seonghyeon/index.html
  week5/seonghyeon/package-lock.json
  week5/seonghyeon/package.json
  week5/seonghyeon/public/vite.svg
  week5/seonghyeon/src/App.jsx
  week5/seonghyeon/src/FilterableProductTable.jsx
  week5/seonghyeon/src/InputBar.jsx
  week5/seonghyeon/src/ProductCategoryRow.jsx
  week5/seonghyeon/src/ProductRow.jsx
  week5/seonghyeon/src/ProductTable.jsx
  week5/seonghyeon/src/SearchBar.jsx
  week5/seonghyeon/src/index.css
  week5/seonghyeon/src/main.jsx
  week5/seonghyeon/vite.config.js
Labels: 조성현

#97 [5주차] 삭제 구현
  week5/hyunju/.gitignore
  week5/hyunju/README.md
  week5/hyunju/eslint.config.js
  week5/hyunju/index.html
  week5/hyunju/package-lock.json
  week5/hyunju/package.json
  week5/hyunju/src/App.jsx
  week5/hyunju/src/FilterableProductTable.jsx
  week5/hyunju/src/InputBar.jsx
  week5/hyunju/src/ProductCategoryRow.jsx
  week5/hyunju/src/ProductRow.jsx
  week5/hyunju/src/ProductTable.jsx
  week5/hyunju/src/SearchBar.jsx
  week5/hyunju/src/main.jsx
  week5/hyunju/vite.config.js
Labels: 이현주

#90 [5주차] 미션 완료
  week5/hyungyu/.gitignore
  week5/hyungyu/README.md
  week5/hyungyu/index.html
  week5/hyungyu/package-lock.json
  week5/hyungyu/package.json
  week5/hyungyu/src/App.jsx
  week5/hyungyu/src/FilterableProductTable.jsx
  week5/hyungyu/src/InputBar.jsx
  week5/hyungyu/src/ProductCategoryRow.jsx
  week5/hyungyu/src/ProductRow.jsx
  week5/hyungyu/src/ProductTable.jsx
  week5/hyungyu/src/SearchBar.jsx
  week5/hyungyu/src/main.jsx
  week5/hyungyu/vite.config.js
Labels: 고현규

#96 [5주차] 삭제 기능 구현 완료
  week4/sooa/src/components/Content.jsx
  week5/sooa/.gitignore
  week5/sooa/README.md
  week5/sooa/eslint.config.js
  week5/sooa/index.html
  week5/sooa/package-lock.json
  week5/sooa/package.json
  week5/sooa/src/App.jsx
  week5/sooa/src/FilterableProductTable.jsx
  week5/sooa/src/InputBar.jsx
  week5/sooa/src/ProductCategoryRow.jsx
  week5/sooa/src/ProductRow.jsx
  week5/sooa/src/ProductTable.jsx
  week5/sooa/src/SearchBar.jsx
  week5/sooa/src/main.jsx
  week5/sooa/vite.config.js
Labels: 이수아

#94 [5주차] delete 기능 구현 완료
  week5/rlawngP91/.gitignore
  week5/rlawngP91/README.md
  week5/rlawngP91/eslint.config.js
  week5/rlawngP91/index.html
  week5/rlawngP91/package-lock.json
  week5/rlawngP91/package.json
  week5/rlawngP91/public/vite.svg
  week5/rlawngP91/src/App.jsx
  week5/rlawngP91/src/FilterableProductTable.jsx
  week5/rlawngP91/src/InputBar.jsx
  week5/rlawngP91/src/ProductCategoryRow.jsx
  week5/rlawngP91/src/ProductRow.jsx
  week5/rlawngP91/src/ProductTable.jsx
  week5/rlawngP91/src/SearchBar.jsx
  week5/rlawngP91/src/main.jsx
  week5/rlawngP91/vite.config.js
Labels: 김주혜

#92 [5주차] delete, edit 구현 완료
  week5/jiyeKa/.gitignore
  week5/jiyeKa/README.md
  week5/jiyeKa/eslint.config.js
  week5/jiyeKa/index.html
  week5/jiyeKa/package-lock.json
  week5/jiyeKa/package.json
  week5/jiyeKa/public/vite.svg
  week5/jiyeKa/src/App.jsx
  week5/jiyeKa/src/FilterableProductTable.jsx
  week5/jiyeKa/src/InputBar.jsx
  week5/jiyeKa/src/ProductCategoryRow.jsx
  week5/jiyeKa/src/ProductRow.jsx
  week5/jiyeKa/src/ProductTable.jsx
  week5/jiyeKa/src/SearchBar.jsx
  week5/jiyeKa/src/main.jsx
  week5/jiyeKa/vite.config.js
Labels: 김지예

#95 [5주차] 삭제, 수정 메서드 구현
  week5/fr0gydev/.gitignore
  week5/fr0gydev/README.md
  week5/fr0gydev/eslint.config.js
  week5/fr0gydev/index.html
  week5/fr0gydev/package-lock.json
  week5/fr0gydev/package.json
  week5/fr0gydev/src/App.jsx
  week5/fr0gydev/src/FilterableProductTable.jsx
  week5/fr0gydev/src/InputBar.jsx
  week5/fr0gydev/src/ProductCategoryRow.jsx
  week5/fr0gydev/src/ProductRow.jsx
  week5/fr0gydev/src/ProductTable.jsx
  week5/fr0gydev/src/SearchBar.jsx
  week5/fr0gydev/src/main.jsx
  week5/fr0gydev/vite.config.js
Labels: 이지현

#93 5주차 실습(삭제, 수정) 구현
  week5/jisung/.gitignore
  week5/jisung/README.md
  week5/jisung/eslint.config.js
  week5/jisung/index.html
  week5/jisung/package-lock.json
  week5/jisung/package.json
  week5/jisung/src/App.jsx
  week5/jisung/src/FilterableProductTable.jsx
  week5/jisung/src/InputBar.jsx
  week5/jisung/src/ProductCategoryRow.jsx
  week5/jisung/src/ProductRow.jsx
  week5/jisung/src/ProductTable.jsx
  week5/jisung/src/SearchBar.jsx
  week5/jisung/src/main.jsx
  week5/jisung/vite.config.js
Labels: 임지성

#103 [6주차] mission 완료
  package-lock.json
  package.json
  week6/hamxxn/mission/.gitignore
  week6/hamxxn/mission/README.md
  week6/hamxxn/mission/eslint.config.js
  week6/hamxxn/mission/index.html
  week6/hamxxn/mission/package-lock.json
  week6/hamxxn/mission/package.json
  week6/hamxxn/mission/public/vite.svg
  week6/hamxxn/mission/src/App.css
  week6/hamxxn/mission/src/App.jsx
  week6/hamxxn/mission/src/assets/battery.svg
  week6/hamxxn/mission/src/assets/bottomBar.svg
  week6/hamxxn/mission/src/assets/color-star.svg
  week6/hamxxn/mission/src/assets/left-chevron.svg
  week6/hamxxn/mission/src/assets/mobile.svg
  week6/hamxxn/mission/src/assets/pizza.svg
  week6/hamxxn/mission/src/assets/plus.svg
  week6/hamxxn/mission/src/assets/react.svg
  week6/hamxxn/mission/src/assets/right-chevron.svg
  week6/hamxxn/mission/src/assets/star.svg
  week6/hamxxn/mission/src/assets/warning.svg
  week6/hamxxn/mission/src/assets/wifi.svg
  week6/hamxxn/mission/src/components/Button.jsx
  week6/hamxxn/mission/src/components/FoodCategory/FoodCategory.jsx
  week6/hamxxn/mission/src/components/FoodCategory/FoodCategory.styles.jsx
  week6/hamxxn/mission/src/components/MenuItem/MenuItem.jsx
  week6/hamxxn/mission/src/components/MenuItem/MenuItem.styles.jsx
  week6/hamxxn/mission/src/components/OrderBar/OrderBar.jsx
  week6/hamxxn/mission/src/components/OrderBar/OrderBar.styles.jsx
  week6/hamxxn/mission/src/components/OrderBarColumn/OrderBar.jsx
  week6/hamxxn/mission/src/components/OrderBarColumn/OrderBar.styles.jsx
  week6/hamxxn/mission/src/components/OrderMenuItem/OrderMenuItem.jsx
  week6/hamxxn/mission/src/components/OrderMenuItem/OrderMenuItem.styles.jsx
  week6/hamxxn/mission/src/components/StatusBar/StatusBar.jsx
  week6/hamxxn/mission/src/components/StatusBar/StausBar.styles.jsx
  week6/hamxxn/mission/src/components/StoreDetail/StoreDetail.jsx
  week6/hamxxn/mission/src/components/StoreDetail/StoreDetail.styles.jsx
  week6/hamxxn/mission/src/main.jsx
  week6/hamxxn/mission/src/models/stores.js
  week6/hamxxn/mission/src/pages/Cart/Cart.jsx
  week6/hamxxn/mission/src/pages/Cart/Cart.styles.jsx
  week6/hamxxn/mission/src/pages/Home/Categorys.jsx
  week6/hamxxn/mission/src/pages/Home/Home.jsx
  week6/hamxxn/mission/src/pages/Home/Main.jsx
  week6/hamxxn/mission/src/pages/Router.jsx
  week6/hamxxn/mission/src/pages/Store/Store.jsx
  week6/hamxxn/mission/src/pages/Store/Store.styles.jsx
  week6/hamxxn/mission/src/pages/Store/cartStore.jsx
  week6/hamxxn/mission/src/pages/Stores/Store.styles.jsx
  week6/hamxxn/mission/src/pages/Stores/Stores.jsx
  week6/hamxxn/mission/src/reset.css
  week6/hamxxn/mission/vite.config.js
Labels: 권동희

#104 6주차 미션
  week6/uchan0/lecture/.gitignore
  week6/uchan0/lecture/README.md
  week6/uchan0/lecture/eslint.config.js
  week6/uchan0/lecture/index.html
  week6/uchan0/lecture/package-lock.json
  week6/uchan0/lecture/package.json
  week6/uchan0/lecture/public/vite.svg
  week6/uchan0/lecture/src/App.jsx
  week6/uchan0/lecture/src/assets/react.svg
  week6/uchan0/lecture/src/main.jsx
  week6/uchan0/lecture/src/pages/Router.jsx
  week6/uchan0/lecture/src/pages/home/Home.jsx
  week6/uchan0/lecture/src/pages/home/Home.module.css
  week6/uchan0/lecture/src/pages/page/Page.jsx
  week6/uchan0/lecture/src/pages/pageId/PageId.jsx
  week6/uchan0/lecture/vite.config.js
  week6/uchan0/mission/.gitignore
  week6/uchan0/mission/README.md
  week6/uchan0/mission/eslint.config.js
  week6/uchan0/mission/index.html
  week6/uchan0/mission/package-lock.json
  week6/uchan0/mission/package.json
  week6/uchan0/mission/public/vite.svg
  week6/uchan0/mission/reset.css
  week6/uchan0/mission/src/App.jsx
  week6/uchan0/mission/src/assets/Caution.png
  week6/uchan0/mission/src/assets/PlusIcon.png
  week6/uchan0/mission/src/assets/Star.png
  week6/uchan0/mission/src/assets/YellowStar.png
  week6/uchan0/mission/src/assets/arrow/arrowBackIcon.png
  week6/uchan0/mission/src/assets/arrow/arrowRightIcon.png
  week6/uchan0/mission/src/assets/foodCategory/pizzaIcon.png
  week6/uchan0/mission/src/assets/react.svg
  week6/uchan0/mission/src/components/Button.jsx
  week6/uchan0/mission/src/components/Button.module.css
  week6/uchan0/mission/src/components/MenuItem/MenuItem.jsx
  week6/uchan0/mission/src/components/MenuItem/MenuItem.module.css
  week6/uchan0/mission/src/components/MenuItem/MenuItem.styles.jsx
  week6/uchan0/mission/src/components/OrderBar/OrderBar.jsx
  week6/uchan0/mission/src/components/OrderBar/OrderBar.module.css
  week6/uchan0/mission/src/components/OrderBar/OrderBar.styles.jsx
  week6/uchan0/mission/src/components/OrderItems/OrderItems.jsx
  week6/uchan0/mission/src/components/OrderItems/OrderItems.module.css
  week6/uchan0/mission/src/components/StoreItems/StoreItems.jsx
  week6/uchan0/mission/src/components/StoreItems/StoreItems.module.css
  week6/uchan0/mission/src/components/categoryItem/CategoryItem.jsx
  week6/uchan0/mission/src/components/categoryItem/CategoryItem.module.css
  week6/uchan0/mission/src/main.jsx
  week6/uchan0/mission/src/models/stores.js
  week6/uchan0/mission/src/pages/Cart/Cart.jsx
  week6/uchan0/mission/src/pages/Cart/Cart.module.css
  week6/uchan0/mission/src/pages/Home/Home.jsx
  week6/uchan0/mission/src/pages/Home/Home.module.css
  week6/uchan0/mission/src/pages/Router.jsx
  week6/uchan0/mission/src/pages/Store/Store.jsx
  week6/uchan0/mission/src/pages/Store/Store.module.css
  week6/uchan0/mission/src/pages/Stores/Stores.jsx
  week6/uchan0/mission/src/pages/Stores/Stores.module.css
  week6/uchan0/mission/src/store/cartStore.js
  week6/uchan0/mission/vite.config.js
Labels: 유찬영

#105 6주차 미션 완료
  week6/gyuun/mission/.gitignore
  week6/gyuun/mission/README.md
  week6/gyuun/mission/index.html
  week6/gyuun/mission/package-lock.json
  week6/gyuun/mission/package.json
  week6/gyuun/mission/public/arrow.svg
  week6/gyuun/mission/public/blackbar.svg
  week6/gyuun/mission/public/bunsik.svg
  week6/gyuun/mission/public/chbam.svg
  week6/gyuun/mission/public/chicken.svg
  week6/gyuun/mission/public/coffee.svg
  week6/gyuun/mission/public/donut.svg
  week6/gyuun/mission/public/goldstar.svg
  week6/gyuun/mission/public/ham.svg
  week6/gyuun/mission/public/koreafood.svg
  week6/gyuun/mission/public/pasta.svg
  week6/gyuun/mission/public/pizza.svg
  week6/gyuun/mission/public/plusa.svg
  week6/gyuun/mission/public/salad.svg
  week6/gyuun/mission/public/sandwich.svg
  week6/gyuun/mission/public/star.svg
  week6/gyuun/mission/public/time.svg
  week6/gyuun/mission/public/vite.svg
  week6/gyuun/mission/public/wify.svg
  week6/gyuun/mission/src/App.jsx
  week6/gyuun/mission/src/assets/react.svg
  week6/gyuun/mission/src/components/Button.jsx
  week6/gyuun/mission/src/components/MenuItem/MenuItem.jsx
  week6/gyuun/mission/src/components/MenuItem/MenuItem.styles.jsx
  week6/gyuun/mission/src/components/OrderBar/OrderBar.jsx
  week6/gyuun/mission/src/components/OrderBar/OrderBar.styles.jsx
  week6/gyuun/mission/src/main.jsx
  week6/gyuun/mission/src/models/stores.js
  week6/gyuun/mission/src/pages/Cart/Cart.jsx
  week6/gyuun/mission/src/pages/Cart/Cart.module.css
  week6/gyuun/mission/src/pages/Home/Home.jsx
  week6/gyuun/mission/src/pages/Home/home.module.css
  week6/gyuun/mission/src/pages/Router.jsx
  week6/gyuun/mission/src/pages/Store/Store.jsx
  week6/gyuun/mission/src/pages/Store/Store.module.css
  week6/gyuun/mission/src/pages/Stores/Stores.jsx
  week6/gyuun/mission/src/pages/Stores/Stores.module.css
  week6/gyuun/mission/src/pages/topbar.module.css
  week6/gyuun/mission/vite.config.js
Labels: 황규운

#113 [6주차] 라우팅 및 화면구현
  week6/Kjiw0n/mission/.gitignore
  week6/Kjiw0n/mission/README.md
  week6/Kjiw0n/mission/index.html
  week6/Kjiw0n/mission/package-lock.json
  week6/Kjiw0n/mission/package.json
  week6/Kjiw0n/mission/src/App.jsx
  week6/Kjiw0n/mission/src/assets/Star1.svg
  week6/Kjiw0n/mission/src/assets/StatusBar.svg
  week6/Kjiw0n/mission/src/assets/WarnningIcon.svg
  week6/Kjiw0n/mission/src/assets/arrowBack.svg
  week6/Kjiw0n/mission/src/assets/meatballsMenu.svg
  week6/Kjiw0n/mission/src/assets/pizza.svg
  week6/Kjiw0n/mission/src/assets/vite.svg
  week6/Kjiw0n/mission/src/components/BackBtn.jsx
  week6/Kjiw0n/mission/src/components/Button.jsx
  week6/Kjiw0n/mission/src/components/Cart/CartInfo.jsx
  week6/Kjiw0n/mission/src/components/Cart/CartItem.jsx
  week6/Kjiw0n/mission/src/components/Cart/CartList.jsx
  week6/Kjiw0n/mission/src/components/Cart/Order.jsx
  week6/Kjiw0n/mission/src/components/Home/FoodCategory.jsx
  week6/Kjiw0n/mission/src/components/MenuItem/MenuItem.jsx
  week6/Kjiw0n/mission/src/components/OrderBar/OrderBar.jsx
  week6/Kjiw0n/mission/src/components/Store/StoreDetailInfo.jsx
  week6/Kjiw0n/mission/src/components/Store/StoreListItem.jsx
  week6/Kjiw0n/mission/src/main.jsx
  week6/Kjiw0n/mission/src/models/stores.js
  week6/Kjiw0n/mission/src/pages/Cart/Cart.jsx
  week6/Kjiw0n/mission/src/pages/Home/Home.jsx
  week6/Kjiw0n/mission/src/pages/Router/Layout.jsx
  week6/Kjiw0n/mission/src/pages/Router/Router.jsx
  week6/Kjiw0n/mission/src/pages/Store/Store.css
  week6/Kjiw0n/mission/src/pages/Store/Store.jsx
  week6/Kjiw0n/mission/src/pages/Stores/Stores.jsx
  week6/Kjiw0n/mission/src/styles/FontStyle.jsx
  week6/Kjiw0n/mission/src/styles/GlobalStyle.jsx
  week6/Kjiw0n/mission/vite.config.js
Labels: 김지원

#150 [9주차]
  week9/hamxxn/todo/app.js
  week9/hamxxn/todo/app.ts
  week9/hamxxn/todo/db.json
  week9/hamxxn/todo/index.css
  week9/hamxxn/todo/index.html
  week9/hamxxn/todo/tsconfig.json
Labels: 권동희
